set(WITH_QT ON CACHE BOOL "")
set(WITH_OPENGL ON CACHE BOOL "")
set(BUILD_TESTS OFF CACHE BOOL "")
set(BUILD_TESTING OFF CACHE BOOL "")
set(BUILD_PERF_TESTS OFF CACHE BOOL "")
set(BUILD_EXAMPLES OFF CACHE BOOL "")

set(Qt5_DIR "${ThirdPartyPath}/QT_5.14.1_msvc2017_64/lib/cmake/Qt5" CACHE PATH "")
set(Qt5Concurrent_DIR "${ThirdPartyPath}/QT_5.14.1_msvc2017_64/lib/cmake/Qt5Concurrent" CACHE PATH "")
set(Qt5Core_DIR "${ThirdPartyPath}/QT_5.14.1_msvc2017_64/lib/cmake/Qt5Core" CACHE PATH "")
set(Qt5Gui_DIR "${ThirdPartyPath}/QT_5.14.1_msvc2017_64/lib/cmake/Qt5Gui" CACHE PATH "")
set(Qt5OpenGL_DIR "${ThirdPartyPath}/QT_5.14.1_msvc2017_64/lib/cmake/Qt5OpenGL" CACHE PATH "")
set(Qt5Test_DIR "${ThirdPartyPath}/QT_5.14.1_msvc2017_64/lib/cmake/Qt5Test" CACHE PATH "")
set(Qt5Widgets_DIR "${ThirdPartyPath}/QT_5.14.1_msvc2017_64/lib/cmake/Qt5Widgets" CACHE PATH "")

